# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
  - 3.5    

global:
  - OE_LICENSE="$HOME/oe_license.txt"
  - PACKAGENAME="minidrugbank"


before_install:
  # Unpack encrypted OpenEye license file
    - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; openssl aes-256-cbc -K $encrypted_a755ba9fa4fd_key -iv $encrypted_a755ba9fa4fd_iv -in oe_license.txt.enc -out OE_LICENSE -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ]; then echo "OpenEye licese will not be installed in forks."; fi

install:
  # pull in requirements from install file
  - source devtools/travis-ci/install.sh
  # Build out the environment
  - hash -r
  # set to always say yes to conda install
  - conda config --set always_yes yes --set changeps1 no
  # makes installs a little more quiet so you get less output
  - conda update -q conda
  - conda info -a
  # creates environment for the given python version
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy pytest 
  - source activate test 
  - conda install -c omnia openforcefield=0.0.2
  - conda list
  - pip install -i https://pypi.anaconda.org/openeye/simple openeye-toolkits

before_script:
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  - python -c 'from openeye import oechem; print(oechem.OEChemGetVersion())'
  - pip install -e .

script:
  - py.test -v -s --durations=5

notifications:
  email: false

#after_success:
#- codecov
#


