package:
  name: minidrugbank 
  version: 0.0.0

source:
  path: ../..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - networkx
    - openmoltools >=0.7.3
    - parmed
    - matplotlib
    - pandas
    - os

test:
  requires:
    - nose
    - nose-timer
  imports:

about:
  home: https://github.com/openforcefield/minidrugbank
  license: MIT
